// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_5s3yy0yvoJ3A0cHfyXS2TWT9KMGGdnw',
    appId: '1:789094005698:web:861dbde151a4e8ff1f745b',
    messagingSenderId: '789094005698',
    projectId: 'flavor-59670',
    authDomain: 'flavor-59670.firebaseapp.com',
    storageBucket: 'flavor-59670.appspot.com',
    measurementId: 'G-BHFZ24ZT5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ7VF-pen19AsLiWf2_dbqDiJUUMwcaho',
    appId: '1:789094005698:android:be6a2b3925ffbe6e1f745b',
    messagingSenderId: '789094005698',
    projectId: 'flavor-59670',
    storageBucket: 'flavor-59670.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDTgTp3Wf-My0W8F3lKiSZiW7QIbiEeI0',
    appId: '1:789094005698:ios:8ead4c5361033d3c1f745b',
    messagingSenderId: '789094005698',
    projectId: 'flavor-59670',
    storageBucket: 'flavor-59670.appspot.com',
    iosClientId: '789094005698-cabd8grrp488nvsd98bl555jqk54luqg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flavor',
  );
}
