# validates any pull request that has master branch as base
# this validations will first find all pubspec.yaml files and then
# run their configurations in parallel
name: pull-request
on:
  pull_request:
    branches: [master]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - run: flutter --version
      - name: pub-get-all
        run: make pub-get-all
      - name: Analyze
        run: make analyze-all
      - name: Run tests
        run: make test-all
